# Generated by Django 4.2.7 on 2025-10-12 11:33

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUserProxy",
            fields=[],
            options={
                "verbose_name": "Yönetici",
                "verbose_name_plural": "Yöneticiler",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
