# Generated by Django 4.2.7 on 2025-10-11 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password_plain', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioned_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oluşturulan Kimlik Bilgisi',
                'verbose_name_plural': 'Oluşturulan Kimlik Bilgileri',
                'ordering': ['-created_at'],
            },
        ),
    ]
