# Generated by Django 4.2.7 on 2025-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_provisionedcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
    ]
