# Generated by Django 4.2.7 on 2025-10-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Hizmet Başlığı"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("fa-bolt", "Yıldırım"),
                            ("fa-plug", "Fiş"),
                            ("fa-drafting-compass", "Pergel"),
                            ("fa-transformer", "Transformatör"),
                            ("fa-cogs", "Dişliler"),
                            ("fa-tools", "Aletler"),
                            ("fa-hard-hat", "Baret"),
                            ("fa-lightbulb", "Ampul"),
                            ("fa-solar-panel", "Solar Panel"),
                            ("fa-charging-station", "Şarj İstasyonu"),
                        ],
                        default="fa-cogs",
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(max_length=300, verbose_name="Alt Başlık"),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "scope_items",
                    models.TextField(
                        help_text="Her satıra bir madde yazın",
                        verbose_name="Kapsam Maddeleri",
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        help_text="Her satıra bir özellik yazın",
                        verbose_name="Avantajlar/Özellikler",
                    ),
                ),
                (
                    "process_steps",
                    models.JSONField(
                        blank=True,
                        help_text='[{"title": "Adım 1", "description": "Açıklama"}] formatında',
                        null=True,
                        verbose_name="Süreç Adımları",
                    ),
                ),
                (
                    "standards",
                    models.TextField(
                        blank=True,
                        help_text="Her satıra bir standart yazın",
                        verbose_name="Standartlar",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıralama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hizmet Kategorisi",
                "verbose_name_plural": "Hizmet Kategorileri",
                "ordering": ["order", "title"],
            },
        ),
    ]
