# Generated by Django 4.2.7 on 2025-10-14 15:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_servicecategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ad Soyad")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Ünvan/Pozisyon"),
                ),
                ("bio", models.TextField(verbose_name="Biyografi/Açıklama")),
                (
                    "image",
                    models.ImageField(
                        help_text="Tercihen kare (1:1) oran ve minimum 400x400px boyutunda",
                        upload_to=core.models.team_member_image_path,
                        verbose_name="Fotoğraf",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıralama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ekip Üyesi",
                "verbose_name_plural": "Ekip Üyeleri",
                "ordering": ["order", "name"],
            },
        ),
    ]
