# Generated by Django 4.2.7 on 2025-10-19 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_sitesettings_google_search_console_and_more"),
    ]

    operations = []
