# Generated by Django 4.2.7 on 2025-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_database_optimizations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Aktivite Kaydı",
                "verbose_name_plural": "Aktivite Kayıtları",
            },
        ),
        migrations.AlterModelTableComment(
            name="activitylog",
            table_comment="Kullanıcı aktivite logları",
        ),
        migrations.AlterModelTableComment(
            name="contactmessage",
            table_comment="İletişim formu mesajları",
        ),
        migrations.AlterModelTableComment(
            name="servicecategory",
            table_comment="Hizmet kategorileri - dinamik hizmet tanımları",
        ),
        migrations.AlterModelTableComment(
            name="sitesettings",
            table_comment="Site genel ayarları - tekil kayıt",
        ),
        migrations.AlterModelTableComment(
            name="teammember",
            table_comment="Ekip üyeleri - hakkımızda sayfası için",
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["-created_at"], name="activity_created_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "-created_at"], name="activity_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["action", "-created_at"], name="activity_action_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(fields=["-created_at"], name="contact_created_idx"),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["status", "-created_at"], name="contact_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(fields=["email"], name="contact_email_idx"),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["is_active", "order"], name="svc_cat_active_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(fields=["slug"], name="svc_cat_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["is_active", "order"], name="team_active_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(fields=["slug"], name="team_slug_idx"),
        ),
    ]
