# Generated by Django 4.2.7 on 2025-10-19 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0003_fix_firm_user_field"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="firm",
            table_comment="Firma bilgileri - müşteri firmaların kayıtları",
        ),
        migrations.AlterModelTableComment(
            name="firmservicehistory",
            table_comment="Firma hizmet geçmişi - eski kayıtlar için",
        ),
        migrations.AlterField(
            model_name="firm",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="E-posta",
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Firma Adı"
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Geçerli bir telefon numarası girin.",
                        regex="^\\+?[\\d\\s\\-()]{10,15}$",
                    )
                ],
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="tax_number",
            field=models.CharField(
                blank=True,
                help_text="10 haneli vergi numarası",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_tax_number",
                        message="Vergi numarası 10 haneli olmalıdır.",
                        regex="^\\d{10}$",
                    )
                ],
                verbose_name="Vergi No",
            ),
        ),
        migrations.AddIndex(
            model_name="firm",
            index=models.Index(fields=["-registration_date"], name="firm_reg_date_idx"),
        ),
        migrations.AddIndex(
            model_name="firm",
            index=models.Index(
                fields=["status", "-registration_date"], name="firm_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="firm",
            index=models.Index(fields=["city", "status"], name="firm_city_status_idx"),
        ),
        migrations.AddIndex(
            model_name="firmservicehistory",
            index=models.Index(
                fields=["firm", "-service_date"], name="firmhist_firm_date_idx"
            ),
        ),
    ]
