# Generated by Django 4.2.7 on 2025-10-20 13:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firms", "0004_alter_firm_table_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firm",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adres"),
        ),
        migrations.AlterField(
            model_name="firm",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Şehir"),
        ),
        migrations.AlterField(
            model_name="firm",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Yetkili Kişi"
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="country",
            field=models.CharField(
                blank=True, default="Türkiye", max_length=100, verbose_name="Ülke"
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="E-posta",
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Geçerli bir telefon numarası girin.",
                        regex="^\\+?[\\d\\s\\-()]{10,15}$",
                    )
                ],
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="tax_number",
            field=models.CharField(
                blank=True,
                help_text="10 haneli vergi numarası (opsiyonel)",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_tax_number",
                        message="Vergi numarası 10 haneli olmalıdır.",
                        regex="^\\d{10}$",
                    )
                ],
                verbose_name="Vergi No",
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Kullanıcı hesabı otomatik olarak oluşturulur",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="firm",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
