# Generated by Django 4.2.7 on 2025-10-11 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Firma Adı')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='Vergi No')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(verbose_name='Adres')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('country', models.CharField(default='Türkiye', max_length=100, verbose_name='Ülke')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Yetkili Kişi')),
                ('contact_person_title', models.CharField(blank=True, max_length=255, verbose_name='Yetkili Unvanı')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif'), ('suspended', 'Askıda')], default='active', max_length=10)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='FirmServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=255, verbose_name='Hizmet Türü')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('service_date', models.DateField(verbose_name='Hizmet Tarihi')),
                ('completion_date', models.DateField(verbose_name='Tamamlanma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='firms.firm')),
            ],
            options={
                'verbose_name': 'Firma Hizmet Geçmişi',
                'verbose_name_plural': 'Firma Hizmet Geçmişleri',
                'ordering': ['-service_date'],
            },
        ),
    ]
