# Generated by Django 4.2.7 on 2025-10-12 11:33

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def ensure_no_null_users(apps, schema_editor):
    """Ensure no Firm records have null user values"""
    Firm = apps.get_model('firms', 'Firm')
    # Delete any Firm records with null user (shouldn't happen but just in case)
    Firm.objects.filter(user__isnull=True).delete()


def reverse_ensure_no_null_users(apps, schema_editor):
    """Reverse operation - nothing to do"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0002_alter_firm_user"),
    ]

    operations = [
        # First, ensure no null users exist
        migrations.RunPython(ensure_no_null_users, reverse_ensure_no_null_users),
        
        # Then, make the field non-nullable
        migrations.AlterField(
            model_name='firm',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='firm', 
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
