# Generated by Django 4.2.7 on 2025-10-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0005_alter_firm_address_alter_firm_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif')], default='active', max_length=10),
        ),
    ]
