# Generated by Django 4.2.7 on 2025-10-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='requested_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='İstenen Tamamlanma Tarihi'),
        ),
    ]
