# Generated by Django 4.2.7 on 2025-10-11 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('electrical_control', 'Elektriksel Periyodik Kontrol'), ('transformer_consultancy', 'Trafo Müşavirlik'), ('electrical_design', 'Elektrik Proje Çizimi')], max_length=50, verbose_name='Hizmet Türü')),
                ('title', models.CharField(max_length=255, verbose_name='Talep Başlığı')),
                ('description', models.TextField(verbose_name='Talep Açıklaması')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tracking_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='firms.firm')),
            ],
            options={
                'verbose_name': 'Hizmet Talebi',
                'verbose_name_plural': 'Hizmet Talepleri',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hizmet Adı')),
                ('service_type', models.CharField(choices=[('electrical_control', 'Elektriksel Periyodik Kontrol'), ('transformer_consultancy', 'Trafo Müşavirlik'), ('electrical_design', 'Elektrik Proje Çizimi')], max_length=50, verbose_name='Hizmet Türü')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_services', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='firms.firm')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['-request_date'],
            },
        ),
    ]
