# Generated by Django 4.2.7 on 2025-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_servicerequest_admin_response_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="service",
            table_comment="Hizmet kayıtları - müşteri hizmetlerinin detayları",
        ),
        migrations.AlterModelTableComment(
            name="servicerequest",
            table_comment="Hizmet talepleri - müşterilerden gelen yeni hizmet istekleri",
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["-request_date"], name="service_request_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["firm", "status"], name="service_firm_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["status", "-request_date"], name="service_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["-completion_date"], name="service_completion_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["-request_date"], name="svcreq_request_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["firm", "status"], name="svcreq_firm_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["status", "-request_date"], name="svcreq_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["tracking_code"], name="svcreq_tracking_code_idx"
            ),
        ),
    ]
