# Generated by Django 4.2.7 on 2025-10-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
