# Generated by Django 4.2.7 on 2025-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_adminuserproxy"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="customuser",
            table_comment="Kullanıcılar - sistem erişim hesapları",
        ),
        migrations.AlterModelTableComment(
            name="userprofile",
            table_comment="Kullanıcı profil bilgileri - ek detaylar",
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["user_type", "is_active"], name="user_type_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["-date_joined"], name="user_date_joined_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="user_email_lookup_idx"),
        ),
    ]
