# Generated by Django 4.2.7 on 2025-10-22 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_table_comment_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
