# Generated by Django 4.2.7 on 2025-10-11 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='SEO URL')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('excerpt', models.TextField(blank=True, verbose_name='Özet')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında'), ('archived', 'Arşivlendi')], default='draft', max_length=20, verbose_name='Durum')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Kapak Görseli')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-created_at'],
            },
        ),
    ]
