# Generated by Django 4.2.7 on 2025-10-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('general', 'Genel'), ('news', 'Haber'), ('tips', 'İpucu')], default='general', max_length=32, verbose_name='Kategori'),
        ),
    ]
