# Generated by Django 4.2.7 on 2025-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogpost_category"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="blogpost",
            table_comment="Blog yazıları - SEO optimized content",
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["-published_at"], name="blog_published_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["status", "-published_at"], name="blog_status_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["-views"], name="blog_views_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["category", "-published_at"], name="blog_cat_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["author", "-published_at"], name="blog_author_pub_idx"
            ),
        ),
    ]
