# Generated by Django 4.2.7 on 2025-10-11 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('document_type', models.CharField(choices=[('service_report', 'Hizmet Raporu'), ('certificate', 'Sertifika'), ('invoice', 'Fatura'), ('contract', 'Sözleşme'), ('technical_drawing', 'Teknik Çizim'), ('other', 'Diğer')], max_length=50, verbose_name='Dosya Türü')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, verbose_name='Dosya')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_visible_to_firm', models.BooleanField(default=True, verbose_name='Firmaya Görünür')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='firms.firm')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='services.service')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doküman',
                'verbose_name_plural': 'Dokümanlar',
                'ordering': ['-upload_date'],
            },
        ),
    ]
