# Generated by Django 4.2.7 on 2025-10-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_parent_document_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='İndirme Sayısı'),
        ),
    ]
