# Generated by Django 4.2.7 on 2025-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_document_download_count"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="document",
            table_comment="Doküman yönetimi - firmalar için dosya saklama",
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["-upload_date"], name="doc_upload_date_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["firm", "-upload_date"], name="doc_firm_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["service", "-upload_date"], name="doc_service_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type", "-upload_date"], name="doc_type_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_visible_to_firm", "-upload_date"],
                name="doc_visible_date_idx",
            ),
        ),
    ]
