# Generated by Django 4.2.7 on 2025-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_image",
            field=models.ImageField(
                blank=True,
                help_text="Önerilen boyut: 800x600px veya 4:3 oran",
                null=True,
                upload_to="site/",
                verbose_name="Hakkımızda Sayfası Görseli",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Önerilen boyut: 1920x1080px veya 16:9 oran",
                null=True,
                upload_to="site/",
                verbose_name="Ana Sayfa Hero Görseli",
            ),
        ),
    ]
