# Generated by Django 4.2.7 on 2025-10-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_sitesettings_about_image_sitesettings_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="google_search_console",
            field=models.CharField(
                blank=True,
                help_text="Meta verification tag içeriği",
                max_length=100,
                verbose_name="Google Search Console Verification",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hotjar_id",
            field=models.CharField(
                blank=True,
                help_text="Kullanıcı davranış analizi için",
                max_length=20,
                verbose_name="Hotjar Site ID",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="google_analytics_id",
            field=models.CharField(
                blank=True,
                help_text="G-XXXXXXXXXX formatında",
                max_length=32,
                verbose_name="Google Analytics ID",
            ),
        ),
    ]
