# Generated by Django 4.2.7 on 2025-10-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_activitylog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Önerilen boyut: 800x450px (16:9 oran) - Kartlarda gösterilir",
                null=True,
                upload_to="services/",
                verbose_name="Hizmet Görseli",
            ),
        ),
    ]
