# Generated by Django 4.2.7 on 2025-10-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_servicecategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtitle",
            field=models.TextField(
                default="BYF Mühendislik olarak, elektriksel periyodik kontrol, trafo müşavirlik ve elektrik proje çizimi alanlarında uzman çözümler sunuyoruz. Kalite, güvenlik ve müşteri memnuniyeti önceliğimizdir.",
                help_text="Ana sayfa hero bölümündeki açıklama metni",
                verbose_name="Ana Sayfa Hero Alt Başlığı",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_title",
            field=models.CharField(
                default="Profesyonel Mühendislik Çözümleri",
                help_text="Ana sayfa hero bölümündeki ana başlık",
                max_length=200,
                verbose_name="Ana Sayfa Hero Başlığı",
            ),
        ),
    ]
